name: release

on:
  release:
    types: [released, prereleased]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install jdk
        run: sudo apt install openjdk-8-jdk

      - name: install maven
        run: sudo apt install maven

      - name: print versions
        run: |
          lsb_release -a
          java -version
          mvn -v

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: publish
        env:
          TOKEN: ${{ github.token }}
        run: |
          echo "$TOKEN"
          echo "${{ github.token }}"
          mvn deploy -Dregistry=https://maven.pkg.github.com/Liam8 -Dtoken="$TOKEN"